name = "home-loan-tracker"
pages_build_output_dir = "./dist"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "home-loan-tracker"
database_id = "8a3525d0-551d-4450-a9f5-8f864acd36ed"
